const STORE='qr-work-v5';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const fresh={role:'tester',email:'',name:'',accountId:'',refCode:'',balance:0,rate:20,minWithdraw:50,accountStatus:'Approved',payouts:{upi:'',usdt:'',binance:'',paypal:''},tasks:[],withdrawals:[],activities:[],stats:{requests:0,accepted:0,rejected:0,expired:0},users:1};
let state={...fresh,...loadRaw()};
let activeTimer=null;let activeTaskId=null;
function loadRaw(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function addActivity(text){state.activities.unshift({id:uid(),text,time:new Date().toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})});state.activities=state.activities.slice(0,40);save();renderRecent()}
function ensureIdentity(){if(!state.accountId)state.accountId=`USR-${Math.random().toString(36).slice(2,10).toUpperCase()}`;if(!state.refCode)state.refCode=`QW-${Math.random().toString(36).slice(2,8).toUpperCase()}`}
function login(){const email=$('email').value.trim().toLowerCase();const password=$('password').value;if(!/^\S+@\S+\.\S+$/.test(email))return toast('Enter a valid email address.');if(password.length<4)return toast('Password must be at least 4 characters.');state.email=email;state.name=email.split('@')[0];state.role=$('role').value;ensureIdentity();if(!state.tasks.length && state.role==='tester'){state.tasks=[{id:uid(),title:'QR usability test #001',instructions:'Review the assigned QR and complete the authorized usability test. Do not enter passwords, OTPs or UPI PINs.',qr:'https://example.com/authorized-test-001',reward:20,minutes:10,status:'open',createdAt:Date.now(),assignedTo:'all'} ,{id:uid(),title:'Checkout flow test #002',instructions:'Check the authorized checkout flow and report whether the QR opens correctly.',qr:'https://example.com/authorized-test-002',reward:20,minutes:8,status:'open',createdAt:Date.now(),assignedTo:'all'}];}save();openApp();addActivity(`Signed in as ${state.role}`)}
function openApp(){ensureIdentity();$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('avatar').textContent=state.role==='admin'?'A':'T';$('topAvatar').textContent=state.role==='admin'?'A':'T';$('userName').textContent=state.role==='admin'?'Administrator':state.name;$('userRole').textContent=state.role==='admin'?'Admin online':'Tester online';$('adminTab').style.display=state.role==='admin'?'inline-flex':'none';renderAll();go('dashboard')}
function logout(){if(activeTimer){clearInterval(activeTimer);activeTimer=null}activeTaskId=null;$('app').classList.add('hidden');$('auth').classList.remove('hidden');toast('Signed out')}
const titles={dashboard:['OVERVIEW','Good to see you'],work:['QR WORK','Available tasks'],status:['STATUS','QR request status'],payout:['PAYOUT','Payout methods'],admin:['ADMIN','Control center']};
function go(page){if(!$(page))return;if(page==='admin'&&state.role!=='admin')return toast('Administrator access required.');document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(page).classList.remove('hidden');document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.page===page));$('pageTitle')?.remove();if(page==='dashboard')renderDashboard();if(page==='work')renderTasks();if(page==='status')renderStatus();if(page==='payout')renderPayout();if(page==='admin')renderAdmin()}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>go(t.dataset.page)));
function renderAll(){renderDashboard();renderRecent();renderTasks();renderStatus();renderPayout();if(state.role==='admin')renderAdmin()}
function renderDashboard(){ensureIdentity();$('balance').textContent=`₹${state.balance.toFixed(2)}`;$('rateValue').textContent=state.rate;$('rateSmall').textContent=state.rate;$('minWithdraw').textContent=state.minWithdraw;$('withdrawMin').textContent=state.minWithdraw;$('accountStatus').textContent=state.accountStatus;$('requests').textContent=state.stats.requests;$('accepted').textContent=state.stats.accepted;$('rejected').textContent=state.stats.rejected;$('expired').textContent=state.stats.expired;$('refCode').textContent=state.refCode;$('accountId').textContent=state.accountId}
function renderRecent(){$('recent').innerHTML=state.activities.length?state.activities.slice(0,6).map(a=>`<div class="recent-item"><i></i><div><b>${esc(a.text)}</b><small>${esc(a.time)}</small></div></div>`).join(''):'<p class="muted">No activity yet.</p>'}
function qrUrl(value,size=220){return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&margin=10&data=${encodeURIComponent(value)}`}
function renderTasks(){const open=state.tasks.filter(t=>t.status==='open');$('queuePill').textContent=`${open.length} open`;if(!open.length){$('taskList').innerHTML='<div class="empty glass"><div class="empty-icon">✓</div><h2>No open tasks</h2><p>Check again when an administrator publishes new authorized work.</p></div>';return}$('taskList').innerHTML=open.map(t=>`<article class="task-card glass"><div class="task-qr"><img src="${qrUrl(t.qr,180)}" alt="QR for ${esc(t.title)}" loading="lazy"><span>AUTHORIZED TEST</span></div><div class="task-copy"><div class="task-top"><span class="mini-pill">Open</span><span class="reward">₹${Number(t.reward).toFixed(2)}</span></div><h2>${esc(t.title)}</h2><p>${esc(t.instructions)}</p><div class="task-meta"><span>⏱ ${Number(t.minutes)||10} min</span><span>▦ QR test</span><span>Admin review</span></div><button class="btn primary" onclick="startTask('${t.id}')">Start work →</button></div></article>`).join('')}
function startTask(id){if(activeTimer)return toast('Finish the current task first.');const t=state.tasks.find(x=>x.id===id);if(!t||t.status!=='open')return toast('Task is no longer available.');activeTaskId=id;t.status='running';t.startedAt=Date.now();state.stats.requests++;save();addActivity(`Started ${t.title}`);renderStatus();go('work');showActiveTask(t,10)}
function showActiveTask(t,seconds){$('activeWork').classList.remove('hidden');$('activeWork').innerHTML=`<div class="active-head"><div><span class="kicker">ACTIVE TASK</span><h2>${esc(t.title)}</h2></div><span class="mini-pill">Running</span></div><div class="active-grid"><div class="qr-large"><img src="${qrUrl(t.qr,260)}" alt="Active task QR"><small>Review the amount and purpose shown by the authorized provider before continuing.</small></div><div class="timer-box"><div class="big-timer" id="timer">00:${String(seconds).padStart(2,'0')}</div><p>Task window</p><div class="progress"><span id="taskBar"></span></div><div class="warning-box">Never enter passwords, OTPs, UPI PINs or banking credentials into a task.</div></div></div>`;let n=seconds;activeTimer=setInterval(()=>{n--;const pct=((seconds-n)/seconds)*100;if($('timer'))$('timer').textContent=`00:${String(Math.max(0,n)).padStart(2,'0')}`;if($('taskBar'))$('taskBar').style.width=`${pct}%`;if(n<=0){clearInterval(activeTimer);activeTimer=null;t.status='submitted';t.submittedAt=Date.now();save();addActivity(`Submitted ${t.title} for review`);renderTasks();renderStatus();showSubmitted(t)}},1000)}
function showSubmitted(t){$('activeWork').classList.remove('hidden');$('activeWork').innerHTML=`<div class="submitted"><div class="check">✓</div><span class="kicker">SUBMITTED</span><h2>Waiting for admin review</h2><p>Your result for <b>${esc(t.title)}</b> has been submitted.</p><button class="btn secondary" onclick="activeTaskId=null;renderTasks();$('activeWork').classList.add('hidden')">Back to tasks</button></div>`}
function renderStatus(){const vals=[['Requests',state.stats.requests,'blue'],['Accepted',state.stats.accepted,'green'],['Rejected',state.stats.rejected,'red'],['Expired',state.stats.expired,'amber'],['Pending',state.tasks.filter(t=>t.status==='submitted'||t.status==='running').length,'purple']];$('statusGrid').innerHTML=vals.map(v=>`<div class="status-card glass ${v[2]}"><span>${esc(v[0])}</span><strong>${v[1]}</strong><small>Updated instantly</small></div>`).join('');const rows=state.tasks.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('historyTable').innerHTML=rows.length?rows.map(t=>`<div class="history-row"><div><b>${esc(t.title)}</b><small>${new Date(t.createdAt||Date.now()).toLocaleString()}</small></div><span class="status-pill ${t.status}">${t.status}</span><strong>${t.status==='accepted'?`+₹${t.reward}`:'—'}</strong></div>`).join(''):'<p class="muted">No tasks yet.</p>'}
function renderPayout(){ensureIdentity();$('upi').value=state.payouts.upi||'';$('usdt').value=state.payouts.usdt||'';$('binance').value=state.payouts.binance||'';$('paypal').value=state.payouts.paypal||'';$('withdrawBalance').textContent=`₹${state.balance.toFixed(2)}`;const p=state.withdrawals.find(w=>w.status==='pending');$('withdrawNote').textContent=p?`Pending request: ₹${p.amount.toFixed(2)} • ${p.method}`:'No pending withdrawal.'}
function savePayouts(){state.payouts.upi=$('upi').value.trim();state.payouts.usdt=$('usdt').value.trim();state.payouts.binance=$('binance').value.trim();state.payouts.paypal=$('paypal').value.trim();save();addActivity('Payout details updated');toast('Payout details saved')}
function requestWithdrawal(){if(state.balance<state.minWithdraw)return toast(`Minimum withdrawal is ₹${state.minWithdraw}.`);const method=state.payouts.upi?'UPI':state.payouts.usdt?'USDT BEP20':state.payouts.binance?'Binance Pay':state.payouts.paypal?'PayPal':'';if(!method)return toast('Save at least one payout method first.');const w={id:uid(),amount:state.balance,method,status:'pending',createdAt:Date.now()};state.withdrawals.push(w);state.balance=0;save();addActivity(`Withdrawal requested: ₹${w.amount.toFixed(2)} via ${method}`);renderPayout();renderAdmin();toast('Withdrawal request sent for admin review')}
function renderAdmin(){if(state.role!=='admin')return;const open=state.tasks.filter(t=>t.status==='open').length;const pending=state.tasks.filter(t=>t.status==='submitted').length;$('adminOpen').textContent=open;$('adminPending').textContent=pending;$('adminUsers').textContent=state.users||1;$('adminWithdrawals').textContent=state.withdrawals.filter(w=>w.status==='pending').length;$('adminTasks').innerHTML=state.tasks.length?state.tasks.map(t=>`<div class="admin-row"><div><b>${esc(t.title)}</b><small>${esc(t.status)} • ₹${t.reward}</small></div><span class="status-pill ${t.status}">${t.status}</span><button class="link" onclick="reviewTask('${t.id}')">Review</button></div>`).join(''):'<p class="muted">No tasks yet.</p>';$('adminPayouts').innerHTML=state.withdrawals.length?state.withdrawals.map(w=>`<div class="admin-row"><div><b>₹${w.amount.toFixed(2)}</b><small>${esc(w.method)} • ${new Date(w.createdAt).toLocaleString()}</small></div><span class="status-pill ${w.status}">${w.status}</span><button class="link" onclick="reviewWithdrawal('${w.id}')">Review</button></div>`).join(''):'<p class="muted">No withdrawals.</p>'}
function createTask(){if(state.role!=='admin')return toast('Administrator access required.');const title=prompt('Task title');if(!title)return;const reward=Math.max(1,Number(prompt('Reward per accepted task','20'))||20);const qr=prompt('Authorized QR content / URL','https://example.com/authorized-test');if(!qr)return;const instructions=prompt('Task instructions','Complete only the authorized usability test. Never enter passwords, OTPs or UPI PINs.');state.tasks.push({id:uid(),title:title.trim(),reward,qr,instructions:instructions||'',minutes:10,status:'open',createdAt:Date.now(),assignedTo:'all'});save();addActivity(`Admin created ${title.trim()}`);renderAll();go('admin');toast('Task published')}
function reviewTask(id){if(state.role!=='admin')return;const t=state.tasks.find(x=>x.id===id);if(!t)return;const choice=prompt(`Review ${t.title}\nCurrent: ${t.status}\nType ACCEPT, REJECT or EXPIRE`);if(!choice)return;const c=choice.trim().toLowerCase();if(!['accept','reject','expire'].includes(c))return toast('Use ACCEPT, REJECT or EXPIRE.');if(c==='accept'){t.status='accepted';state.stats.accepted++;state.balance+=Number(t.reward);state.stats.requests=Math.max(state.stats.requests,state.stats.accepted+state.stats.rejected+state.stats.expired)}else if(c==='reject'){t.status='rejected';state.stats.rejected++}else{t.status='expired';state.stats.expired++}save();addActivity(`Admin marked ${t.title}: ${t.status}`);renderAll();go('admin');toast(`Task ${t.status}`)}
function reviewWithdrawal(id){if(state.role!=='admin')return;const w=state.withdrawals.find(x=>x.id===id);if(!w)return;const c=prompt(`Withdrawal ₹${w.amount.toFixed(2)} via ${w.method}\nType PAID, REJECT or HOLD`);if(!c)return;const a=c.trim().toLowerCase();if(!['paid','reject','hold'].includes(a))return toast('Use PAID, REJECT or HOLD.');w.status=a==='paid'?'paid':a==='reject'?'rejected':'pending';save();addActivity(`Withdrawal ${w.status}: ₹${w.amount.toFixed(2)}`);renderPayout();renderAdmin();toast(`Withdrawal ${w.status}`)}
async function copyText(id){const txt=$(id).textContent.trim();try{await navigator.clipboard.writeText(txt);toast('Copied')}catch{toast(txt)}}
window.addEventListener('load',()=>{if(state.email){openApp()}else{renderDashboard();renderRecent()}});
