const STORE='qr-work-v3';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>crypto.randomUUID?.()||('id-'+Date.now()+'-'+Math.random().toString(36).slice(2));
const freshState={role:'tester',email:'',balance:0,completed:0,pending:0,available:0,upi:'',activities:[],tasks:[],withdrawals:[]};
let state=load(); let timerId=null; let activeTask=null;
function load(){try{return {...freshState,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return {...freshState}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function addActivity(text){state.activities.unshift({text,time:new Date().toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})});state.activities=state.activities.slice(0,30);save();refreshActivity()}
function login(){const email=$('email').value.trim().toLowerCase();const password=$('password').value;if(!/^\S+@\S+\.\S+$/.test(email))return toast('Enter a valid email address.');if(password.length<4)return toast('Password must be at least 4 characters.');state.email=email;state.role='tester';save();openApp();addActivity('Signed in');}
function openApp(){ $('auth').classList.add('hidden');$('app').classList.remove('hidden');$('avatar').textContent=state.role==='admin'?'A':'T';$('topAvatar').textContent=state.role==='admin'?'A':'T';$('userName').textContent=state.role==='admin'?'Administrator':state.email.split('@')[0];$('userRole').textContent=state.role==='admin'?'Admin online':'Tester online';document.querySelectorAll('.admin-only').forEach(x=>x.style.display=state.role==='admin'?'flex':'none');refresh();go('dashboard') }
function logout(){if(timerId){clearInterval(timerId);timerId=null}activeTask=null;$('app').classList.add('hidden');$('auth').classList.remove('hidden');toast('Signed out')}
const titles={dashboard:['TESTER SPACE','Good to see you'],work:['TASK CENTER','Your next task'],qr:['UTILITY','QR Generator'],history:['RECORDS','Activity & transactions'],admin:['ADMIN CONSOLE','Control center']};
function go(page){if(!$(page))return;if(page==='admin'&&state.role!=='admin')return toast('Administrator access required.');document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(page).classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('sectionEyebrow').textContent=titles[page][0];$('pageTitle').textContent=titles[page][1];if(page==='qr')makeQr();if(page==='work')renderTask();if(page==='history')renderHistory();if(page==='admin')renderAdmin()}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>go(n.dataset.page)));
function refresh(){state.available=state.tasks.filter(t=>t.status==='open').length;$('balance').textContent=`₹${state.balance}`;$('completed').textContent=state.completed;$('pending').textContent=state.pending;$('available').textContent=state.available;const pct=Math.min(100,state.completed*20);$('progressPct').textContent=pct+'%';$('progressBar').style.width=pct+'%';$('lastBar').style.height=Math.max(18,pct)+'%';refreshActivity();renderHistory();if(state.role==='admin')renderAdmin();save()}
function refreshActivity(){$('activity').innerHTML=state.activities.slice(0,6).map(a=>`<div class="activity-item"><i class="dot"></i><div><b>${esc(a.text)}</b><small>${esc(a.time)}</small></div></div>`).join('')||'<p class="muted">No activity yet.</p>'}
function qrUrl(data,size=220){return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&margin=8&data=${encodeURIComponent(data)}`}
function makeQr(){const text=$('qrText').value.trim();const holder=$('qrCanvas').parentElement;if(!text){holder.innerHTML='<div class="qr-empty">Enter a URL or text above.</div>';return}holder.innerHTML=`<img src="${qrUrl(text,220)}" width="220" height="220" alt="Generated QR" referrerpolicy="no-referrer"><small>QR generated</small>`;const img=holder.querySelector('img');img.onerror=()=>{holder.innerHTML='<div class="qr-empty">QR service is unavailable. Try again.</div>'}}
function clearQr(){$('qrText').value='';makeQr()}
function renderTask(){const open=state.tasks.find(t=>t.status==='open');const assigned=activeTask&&state.tasks.find(t=>t.id===activeTask);if(assigned){if(assigned.status==='running')showWaiting();else if(assigned.status==='submitted')showDone();else if(assigned.status==='accepted'||assigned.status==='rejected'||assigned.status==='expired')showResult(assigned);return}if(!open){$('taskReady').innerHTML='<div class="waiting"><div class="success-icon">✓</div><h3>No tasks available</h3><p class="muted">There is no active work right now. Check again after an administrator publishes a task.</p></div>';return}activeTask=open.id;$('taskReady').innerHTML=`<div class="task-grid"><div class="qr-preview"><img src="${qrUrl(open.qr||'https://example.com/qr-work-test',180)}" width="180" height="180" alt="Authorized test QR" referrerpolicy="no-referrer"><small>Authorized test QR</small></div><div><h3>${esc(open.title)}</h3><p class="muted">${esc(open.instructions||'Review the instructions and complete only the authorized test.')}</p><div class="meta"><span>Reward <b>₹${open.reward}</b></span><span>Time <b>~${open.minutes} min</b></span><span>Type <b>Usability</b></span></div><button class="btn primary" onclick="startTask()">Start task →</button></div></div>`;if($('taskStatus'))$('taskStatus').textContent='Ready'}
function startTask(){const t=state.tasks.find(x=>x.id===activeTask);if(!t||t.status!=='open')return toast('This task is no longer available.');t.status='running';t.startedAt=Date.now();state.pending++;save();addActivity(`Started: ${t.title}`);showWaiting();let n=10;$('timer').textContent='00:10';$('waitBar').style.width='0%';timerId=setInterval(()=>{n--;$('timer').textContent='00:'+String(Math.max(0,n)).padStart(2,'0');$('waitBar').style.width=((10-n)*10)+'%';if(n<=0){clearInterval(timerId);timerId=null;t.status='submitted';t.submittedAt=Date.now();save();addActivity(`Test window complete: ${t.title}`);showDone()}},1000)}
function showWaiting(){$('taskReady').classList.add('hidden');$('taskWaiting').classList.remove('hidden');$('taskDone').classList.add('hidden');$('taskStatus').textContent='Running'}
function showDone(){$('taskReady').classList.add('hidden');$('taskWaiting').classList.add('hidden');$('taskDone').classList.remove('hidden');$('taskStatus').textContent='Submitted'}
function showResult(t){$('taskReady').classList.remove('hidden');$('taskWaiting').classList.add('hidden');$('taskDone').classList.add('hidden');const label=t.status==='accepted'?'Accepted':t.status==='rejected'?'Rejected':'Expired';$('taskStatus').textContent=label;$('taskReady').innerHTML=`<div class="waiting"><div class="success-icon">${t.status==='accepted'?'✓':t.status==='rejected'?'×':'!'}</div><h3>Task ${label}</h3><p class="muted">${t.status==='accepted'?`₹${t.reward} has been added to your balance.`:'This task is closed. You can start another available task.'}</p><button class="btn primary" onclick="activeTask=null;renderTask()">Find another task →</button></div>`}
function submitTask(){const t=state.tasks.find(x=>x.id===activeTask);if(!t||t.status!=='submitted')return;toast('Submitted for admin review');refresh()}
function renderHistory(){$('historyList').innerHTML=state.activities.length?state.activities.map(a=>`<div class="history-row"><span><b>${esc(a.text)}</b><small>${esc(a.time)}</small></span><span><em class="pill">Recorded</em></span><span>—</span></div>`).join(''):'<p class="muted">No transactions yet.</p>'}
function withdraw(){if(state.balance<20)return toast('Minimum withdrawal balance is ₹20.');const upi=prompt('Enter your UPI ID');if(!upi||!/^[\w.-]+@[\w.-]+$/.test(upi.trim()))return toast('Enter a valid UPI ID.');state.upi=upi.trim();state.withdrawals.push({id:uid(),amount:state.balance,upi:state.upi,status:'pending',createdAt:Date.now()});state.balance=0;addActivity(`Withdrawal requested • ₹${state.withdrawals.at(-1).amount}`);refresh();toast('Withdrawal request sent for admin review')}
function renderAdmin(){const open=state.tasks.filter(t=>t.status==='open').length;const pending=state.tasks.filter(t=>t.status==='submitted').length;$('adminOpen').textContent=open;$('adminTasks').innerHTML=state.tasks.length?state.tasks.map(t=>`<div class="admin-row"><span><b>${esc(t.title)}</b><small>₹${t.reward} • ${esc(t.status)}</small></span><em class="pill">${esc(t.status)}</em><button class="link" onclick="reviewTask('${t.id}')">Review</button></div>`).join(''):`<p class="muted">No tasks yet. Create the first task.</p>`;const q=$('adminReviewCount');if(q)q.textContent=pending}
function createTask(){if(state.role!=='admin')return;const title=prompt('Task title');if(!title)return;const reward=Number(prompt('Reward in ₹','20'));if(!Number.isFinite(reward)||reward<=0)return toast('Invalid reward.');const qr=prompt('QR content / authorized test URL','https://example.com/test');if(!qr)return;const instructions=prompt('Instructions','Scan the QR and complete the authorized usability test. Never enter passwords, OTPs or UPI PINs.');state.tasks.push({id:uid(),title:title.trim(),reward,qr,instructions:instructions||'',minutes:10,status:'open',createdAt:Date.now()});addActivity(`Admin created: ${title.trim()}`);refresh();go('admin');toast('Task published')}
function reviewTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;const action=prompt(`Task: ${t.title}\nStatus: ${t.status}\nType ACCEPT, REJECT, or EXPIRE`);if(!action)return;const a=action.trim().toLowerCase();if(!['accept','reject','expire'].includes(a))return toast('Use ACCEPT, REJECT or EXPIRE.');if(a==='accept'){t.status='accepted';state.pending=Math.max(0,state.pending-1);state.completed++;state.balance+=Number(t.reward)}else if(a==='reject'){t.status='rejected';state.pending=Math.max(0,state.pending-1)}else{t.status='expired';state.pending=Math.max(0,state.pending-1)}addActivity(`${t.title} • ${t.status}`);refresh();toast(`Task ${t.status}`)}
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();go('qr');$('qrText').focus()}});
window.addEventListener('load',()=>{if(state.email)openApp();else{refreshActivity();renderHistory()}});
