const state={role:'tester',balance:0,completed:0,pending:0,available:3,activities:[{text:'Workspace initialized',time:'Now'},{text:'3 tasks available',time:'Now'}],tasks:[{title:'QR usability test #001',status:'Open',reward:20},{title:'Checkout flow test #002',status:'Open',reward:20},{title:'Landing page test #003',status:'Open',reward:20}]};
let timerId=null;
const $=id=>document.getElementById(id);
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2500)}
function login(){const email=$('email').value.trim();if(!email||!email.includes('@'))return toast('Enter a valid email address.');state.role=$('role').value;$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('avatar').textContent=state.role==='admin'?'A':'T';$('topAvatar').textContent=state.role==='admin'?'A':'T';$('userName').textContent=state.role==='admin'?'Administrator':'Tester';$('userRole').textContent=state.role==='admin'?'Admin online':'Tester online';document.querySelectorAll('.admin-only').forEach(x=>x.style.display=state.role==='admin'?'flex':'none');addActivity(`Signed in as ${state.role}`);refresh();go('dashboard')}
function logout(){if(timerId){clearInterval(timerId);timerId=null}$('app').classList.add('hidden');$('auth').classList.remove('hidden');toast('Signed out')}
const titles={dashboard:['TESTER SPACE','Good to see you'],work:['TASK CENTER','Your next task'],qr:['UTILITY','QR Generator'],history:['RECORDS','Activity & transactions'],admin:['ADMIN CONSOLE','Control center']};
function go(page){if(!$(page))return;if(page==='admin'&&state.role!=='admin')return toast('Administrator access required.');document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(page).classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('sectionEyebrow').textContent=titles[page][0];$('pageTitle').textContent=titles[page][1];if(page==='qr')makeQr();if(page==='work')renderTaskQr();if(page==='history')renderHistory();if(page==='admin')renderAdmin()}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>go(n.dataset.page)));
function addActivity(text){state.activities.unshift({text,time:'Just now'});state.activities=state.activities.slice(0,12);refreshActivity();}
function refresh(){ $('balance').textContent=`₹${state.balance}`;$('completed').textContent=state.completed;$('pending').textContent=state.pending;$('available').textContent=state.available;const pct=Math.min(100,state.completed*20);$('progressPct').textContent=pct+'%';$('progressBar').style.width=pct+'%';$('lastBar').style.height=Math.max(18,pct)+'%';refreshActivity();renderHistory();if(state.role==='admin')renderAdmin() }
function refreshActivity(){$('activity').innerHTML=state.activities.slice(0,5).map(a=>`<div class="activity-item"><i class="dot"></i><div><b>${esc(a.text)}</b><small>${esc(a.time)}</small></div></div>`).join('')}
function renderTaskQr(){const host=$('taskQr');if(!host)return;host.innerHTML='';const data=`https://example.com/qr-work-task?id=${encodeURIComponent(Date.now())}`;if(window.QRCode&&typeof QRCode.toCanvas==='function'){const canvas=document.createElement('canvas');host.appendChild(canvas);QRCode.toCanvas(canvas,data,{width:180,margin:2,errorCorrectionLevel:'M'},err=>{if(err){host.innerHTML='';fallbackTaskQr(host,data)}})}else{fallbackTaskQr(host,data)}}
function fallbackTaskQr(host,data){const img=document.createElement('img');img.alt='Task QR';img.width=180;img.height=180;img.loading='eager';img.referrerPolicy='no-referrer';img.src='https://api.qrserver.com/v1/create-qr-code/?size=180x180&margin=8&data='+encodeURIComponent(data);img.onerror=()=>{host.innerHTML='<span style="color:#111;font-size:10px">QR service unavailable</span>'};host.appendChild(img)}
function startTask(){if(timerId)return toast('A task is already running.');if(state.available<=0)return toast('No tasks available.');state.available--;state.pending++;$('available').textContent=state.available;$('pending').textContent=state.pending;$('taskReady').classList.add('hidden');$('taskWaiting').classList.remove('hidden');$('taskStatus').textContent='Waiting';let n=10;$('timer').textContent='00:10';$('waitBar').style.width='0%';addActivity('Task started');timerId=setInterval(()=>{n--;$('timer').textContent='00:'+String(n).padStart(2,'0');$('waitBar').style.width=((10-n)*10)+'%';if(n<=0){clearInterval(timerId);timerId=null;$('taskWaiting').classList.add('hidden');$('taskDone').classList.remove('hidden');$('taskStatus').textContent='Ready';addActivity('Task ready for submission');}},1000)}
function submitTask(){state.pending=Math.max(0,state.pending-1);state.completed++;state.balance+=20;$('taskDone').classList.add('hidden');$('taskReady').classList.remove('hidden');$('taskStatus').textContent='Ready';renderTaskQr();addActivity('Task submitted • ₹20 credited');refresh();toast('Result submitted successfully')}
function makeQr(){const text=$('qrText').value.trim()||'https://example.com/test';const canvas=$('qrCanvas');if(window.QRCode&&typeof QRCode.toCanvas==='function'){canvas.style.display='block';QRCode.toCanvas(canvas,text,{width:190,margin:2,errorCorrectionLevel:'M'},err=>{if(err){$('qrLabel').textContent='QR generation failed';fallbackMainQr(text)}else $('qrLabel').textContent='QR generated locally'})}else{fallbackMainQr(text)}}
function fallbackMainQr(text){const holder=$('qrCanvas').parentElement;holder.innerHTML='';const img=document.createElement('img');img.alt='Generated QR';img.width=190;img.height=190;img.referrerPolicy='no-referrer';img.src='https://api.qrserver.com/v1/create-qr-code/?size=190x190&margin=8&data='+encodeURIComponent(text);img.onerror=()=>{$('qrLabel').textContent='QR service unavailable'};holder.appendChild(img);$('qrLabel').textContent='QR generated'}
function clearQr(){const holder=$('qrCanvas').parentElement;holder.innerHTML='<canvas id="qrCanvas"></canvas><small id="qrLabel">Ready</small>';$('qrText').value=''}
function withdraw(){if(state.balance<20)return toast('Minimum withdrawal balance is ₹20.');state.balance=0;addActivity('Withdrawal request submitted');refresh();toast('Withdrawal request sent for admin review')}
function renderHistory(){$('historyList').innerHTML=state.activities.map(a=>`<div class="history-row"><span><b>${esc(a.text)}</b><small>${esc(a.time)}</small></span><span><em class="pill">Recorded</em></span><span>${a.text.includes('₹20')?'+₹20':'—'}</span></div>`).join('')}
function createTask(){if(state.role!=='admin')return;const n=state.tasks.length+1;state.tasks.push({title:`New testing task #${String(n).padStart(3,'0')}`,status:'Open',reward:20});state.available++;addActivity('Admin created a new task');renderAdmin();refresh();toast('Task created')}
function renderAdmin(){$('adminOpen').textContent=state.tasks.filter(t=>t.status==='Open').length;$('adminTasks').innerHTML=state.tasks.map((t,i)=>`<div class="admin-row"><span><b>${esc(t.title)}</b><small>Reward ₹${t.reward}</small></span><em class="pill">${t.status}</em><button class="link" onclick="approveTask(${i})">${t.status==='Open'?'Approve':'View'}</button></div>`).join('')}
function approveTask(i){const t=state.tasks[i];if(t.status!=='Open')return;t.status='Approved';state.available=Math.max(0,state.available-1);addActivity(`Approved ${t.title}`);renderAdmin();refresh();toast('Task approved')}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();go('qr');$('qrText').focus()}});
window.addEventListener('load',()=>{if(window.QRCode)makeQr();renderTaskQr()});
