const STORE='qr-work-v6';
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const fresh={role:'tester',email:'',name:'',accountId:'',refCode:'',balance:0,rate:25,minWithdraw:50,accountStatus:'Approved',payouts:{upi:'',usdt:'',binance:'',paypal:''},tasks:[],withdrawals:[],activities:[],stats:{requests:0,accepted:0,rejected:0,expired:0}};
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function state(){const r=load();return {...fresh,...r,payouts:{...fresh.payouts,...(r.payouts||{})},stats:{...fresh.stats,...(r.stats||{})},tasks:Array.isArray(r.tasks)?r.tasks:[],withdrawals:Array.isArray(r.withdrawals)?r.withdrawals:[]}}
function save(s){localStorage.setItem(STORE,JSON.stringify(s))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function qrUrl(value,size=220){return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&margin=10&data=${encodeURIComponent(value)}`}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);setTimeout(()=>t.classList.remove('show'),2200)}
function updatePreview(){const value=$('taskQr').value.trim();const img=$('qrPreview');if(!value){img.removeAttribute('src');return}img.src=qrUrl(value,220)}
function render(){const s=state();$('openCount').textContent=s.tasks.filter(t=>t.status==='open').length;$('pendingCount').textContent=s.tasks.filter(t=>t.status==='submitted').length;$('acceptedCount').textContent=s.stats.accepted;$('withdrawalCount').textContent=s.withdrawals.filter(w=>w.status==='pending').length;
$('tasks').innerHTML=s.tasks.length?s.tasks.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(t=>`<div class="row"><div class="row-main"><strong>${esc(t.title)}</strong><small>${esc(t.status)} • ₹${Number(t.reward).toFixed(2)} • ${Number(t.minutes)||10} min</small></div><span class="pill ${t.status}">${esc(t.status)}</span><div class="actions">${t.status==='submitted'?`<button class="accept" onclick="reviewTask('${t.id}','accepted')">Accept</button><button class="reject" onclick="reviewTask('${t.id}','rejected')">Reject</button>`:''}${t.status==='open'?`<button class="expire" onclick="reviewTask('${t.id}','expired')">Expire</button>`:''}</div></div>`).join(''):'<div class="empty">No tasks yet. Create one from the form.</div>';
$('withdrawals').innerHTML=s.withdrawals.length?s.withdrawals.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(w=>`<div class="row"><div class="row-main"><strong>₹${Number(w.amount).toFixed(2)}</strong><small>${esc(w.method)} • ${new Date(w.createdAt||Date.now()).toLocaleString()}</small></div><span class="pill ${w.status}">${esc(w.status)}</span><div class="actions">${w.status==='pending'?`<button class="accept" onclick="reviewWithdrawal('${w.id}','paid')">Mark paid</button><button class="reject" onclick="reviewWithdrawal('${w.id}','rejected')">Reject</button>`:''}</div></div>`).join(''):'<div class="empty">No withdrawal requests.</div>'}
function reviewTask(id,status){const s=state();const t=s.tasks.find(x=>x.id===id);if(!t)return;if(!['accepted','rejected','expired'].includes(status))return;if(['accepted','rejected','expired'].includes(t.status))return toast('This task is already closed.');t.status=status;if(status==='accepted'){s.stats.accepted++;s.balance=Number(s.balance||0)+Number(t.reward||0)}else if(status==='rejected')s.stats.rejected++;else s.stats.expired++;s.activities=Array.isArray(s.activities)?s.activities:[];s.activities.unshift({id:uid(),text:`Admin marked ${t.title}: ${status}`,time:new Date().toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})});save(s);render();toast(`Task ${status}`)}
function reviewWithdrawal(id,status){const s=state();const w=s.withdrawals.find(x=>x.id===id);if(!w||w.status!=='pending')return;if(status==='paid'){w.status='paid'}else if(status==='rejected'){w.status='rejected';s.balance=Number(s.balance||0)+Number(w.amount||0)}else return;s.activities=Array.isArray(s.activities)?s.activities:[];s.activities.unshift({id:uid(),text:`Withdrawal ${status}: ₹${Number(w.amount).toFixed(2)}`,time:new Date().toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})});save(s);render();toast(`Withdrawal ${status}`)}
function createTask(e){e.preventDefault();const s=state();const title=$('taskTitle').value.trim();const qr=$('taskQr').value.trim();const reward=Number($('taskReward').value);const minutes=Number($('taskMinutes').value);const instructions=$('taskInstructions').value.trim();if(!title||!qr||reward<=0||minutes<=0)return toast('Fill all task fields correctly.');const task={id:uid(),title,qr,reward,minutes,instructions,status:'open',createdAt:Date.now(),assignedTo:'all'};s.tasks=s.tasks.filter(t=>!(String(t.qr||'').includes('example.com/authorized-test-')));s.tasks.push(task);save(s);$('taskForm').reset();$('taskReward').value=25;$('taskMinutes').value=10;updatePreview();render();toast('QR generated and task published')}
$('taskForm').addEventListener('submit',createTask);$('taskQr').addEventListener('input',updatePreview);$('refresh').addEventListener('click',render);window.addEventListener('storage',render);updatePreview();render();