const STORE='qr-work-v6';
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const fresh={role:'tester',email:'',name:'',accountId:'',refCode:'',balance:0,rate:25,minWithdraw:50,accountStatus:'Approved',payouts:{upi:'',usdt:'',binance:'',paypal:''},tasks:[],withdrawals:[],activities:[],stats:{requests:0,accepted:0,rejected:0,expired:0}};
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function state(){const r=load();return {...fresh,...r,payouts:{...fresh.payouts,...(r.payouts||{})},stats:{...fresh.stats,...(r.stats||{})},tasks:Array.isArray(r.tasks)?r.tasks:[],withdrawals:Array.isArray(r.withdrawals)?r.withdrawals:[]}}
function save(s){localStorage.setItem(STORE,JSON.stringify(s))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);setTimeout(()=>t.classList.remove('show'),2200)}
function updatePreview(){const file=$('taskQrFile').files?.[0],img=$('qrPreview');if(!file){img.removeAttribute('src');return}if(!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('Use PNG, JPG or WebP.');if(file.size>4*1024*1024)return toast('QR image must be smaller than 4 MB.');img.src=URL.createObjectURL(file)}
function imageToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=900;const scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.88))};img.onerror=reject;img.src=String(reader.result)};reader.onerror=reject;reader.readAsDataURL(file)})}
function render(){const s=state();$('openCount').textContent=s.tasks.filter(t=>t.status==='open').length;$('pendingCount').textContent=s.tasks.filter(t=>t.status==='submitted').length;$('acceptedCount').textContent=s.stats.accepted;$('withdrawalCount').textContent=s.withdrawals.filter(w=>w.status==='pending').length;
$('tasks').innerHTML=s.tasks.length?s.tasks.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(t=>`<div class="row"><div class="row-main"><strong>${esc(t.title)}</strong><small>${esc(t.status)} • ₹${Number(t.reward).toFixed(2)} • ${Number(t.minutes)||10} min • ${t.qrImage?'QR photo':'QR data'}</small></div><span class="pill ${t.status}">${esc(t.status)}</span><div class="actions">${t.status==='submitted'?`<button class="accept" onclick="reviewTask('${t.id}','accepted')">Accept</button><button class="reject" onclick="reviewTask('${t.id}','rejected')">Reject</button>`:''}${t.status==='open'?`<button class="expire" onclick="reviewTask('${t.id}','expired')">Expire</button>`:''}</div></div>`).join(''):'<div class="empty">No tasks yet. Upload a QR photo to create one.</div>';
$('withdrawals').innerHTML=s.withdrawals.length?s.withdrawals.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(w=>`<div class="row"><div class="row-main"><strong>₹${Number(w.amount).toFixed(2)}</strong><small>${esc(w.method)} • ${new Date(w.createdAt||Date.now()).toLocaleString()}</small></div><span class="pill ${w.status}">${esc(w.status)}</span><div class="actions">${w.status==='pending'?`<button class="accept" onclick="reviewWithdrawal('${w.id}','paid')">Mark paid</button><button class="reject" onclick="reviewWithdrawal('${w.id}','rejected')">Reject</button>`:''}</div></div>`).join(''):'<div class="empty">No withdrawal requests.</div>'}
function reviewTask(id,status){const s=state();const t=s.tasks.find(x=>x.id===id);if(!t)return;if(!['accepted','rejected','expired'].includes(status))return;if(['accepted','rejected','expired'].includes(t.status))return toast('This task is already closed.');t.status=status;if(status==='accepted'){s.stats.accepted++;s.balance=Number(s.balance||0)+Number(t.reward||0)}else if(status==='rejected')s.stats.rejected++;else s.stats.expired++;s.activities=Array.isArray(s.activities)?s.activities:[];s.activities.unshift({id:uid(),text:`Admin marked ${t.title}: ${status}`,time:new Date().toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})});save(s);render();toast(`Task ${status}`)}
function reviewWithdrawal(id,status){const s=state();const w=s.withdrawals.find(x=>x.id===id);if(!w||w.status!=='pending')return;if(status==='paid')w.status='paid';else if(status==='rejected'){w.status='rejected';s.balance=Number(s.balance||0)+Number(w.amount||0)}else return;s.activities=Array.isArray(s.activities)?s.activities:[];s.activities.unshift({id:uid(),text:`Withdrawal ${status}: ₹${Number(w.amount).toFixed(2)}`,time:new Date().toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})});save(s);render();toast(`Withdrawal ${status}`)}
async function createTask(e){e.preventDefault();const s=state();const title=$('taskTitle').value.trim();const file=$('taskQrFile').files?.[0];const reward=Number($('taskReward').value);const minutes=Number($('taskMinutes').value);const instructions=$('taskInstructions').value.trim();if(!title||!file||reward<=0||minutes<=0)return toast('Add a QR photo and complete the task fields.');if(file.size>4*1024*1024)return toast('QR image must be smaller than 4 MB.');try{const qrImage=await imageToDataUrl(file);const task={id:uid(),title,qrImage,reward,minutes,instructions,status:'open',createdAt:Date.now(),assignedTo:'all'};s.tasks=s.tasks.filter(t=>!String(t.qr||'').includes('example.com/authorized-test-'));s.tasks.push(task);save(s);$('taskForm').reset();$('taskReward').value=25;$('taskMinutes').value=10;$('qrPreview').removeAttribute('src');render();toast('QR photo published to the task queue')}catch{toast('Could not read that image. Try another QR photo.')}}
$('taskForm').addEventListener('submit',createTask);$('taskQrFile').addEventListener('change',updatePreview);$('refresh').addEventListener('click',render);window.addEventListener('storage',render);render();